### ISSUE TITLE
Partner Chain Does Not Support PaymentExtendedSigningKeyShelley_ed25519_bip32

### ISSUE THREAD

**Issue by keishyo** [midnight-ntwrk/partner-chain-deps-docker#4]
I encountered an issue while working with the partner chain, where it does not support:

> PaymentExtendedSigningKeyShelley_ed25519_bip32

I am using CNTools to create the wallet, which generates keys in this type. In order to proceed with the register3 step, it is necessary to convert the signing key from 

> PaymentSigningKeyShelley_ed25519

otherwise, the following error occurs during the key decoding process:

```
The registration transaction could not be submitted: (UnknownContractError "An error occurred when running CTL base monad: Unable to load key from file: \"/home/teko/partner-chains-cli/payment.skey\", error: Error: Error while decoding key
    at _n (file:///home/teko/partner-chains-cli/.index.mjs:7:67660)
    at file:///home/teko/partner-chains-cli/.index.mjs:19:138434
    at TT (file:///home/teko/partner-chains-cli/.index.mjs:7:119995)
    at Object.run (file:///home/teko/partner-chains-cli/.index.mjs:7:122805)
    at bT (file:///home/teko/partner-chains-cli/.index.mjs:7:125160)
    at tDa (file:///home/teko/partner-chains-cli/.index.mjs:7:125470)
    at file:///home/teko/partner-chains-cli/.index.mjs:7:125633
    at BD (file:///home/teko/partner-chains-cli/.index.mjs:7:118775)
    at TT (file:///home/teko/partner-chains-cli/.index.mjs:7:120396)
    at file:///home/teko/partner-chains-cli/.index.mjs:7:122834")
Error: Registration failed
```
Please investigate this issue and consider providing support for _PaymentExtendedSigningKeyShelley_ed25519_bip32_ or propose a conversion method for the signing key to avoid the error.

**Comment by tienna** [comment]
I had the same error at register3 too. 

```
The registration transaction could not be submitted: (UnknownContractError "An error occurred when running CTL base monad: Unable to load key from file: 
"/cnode/priv/wallet/C2VN/payment.skey\", error: Error: Error while decoding key
at _n (file:///hme/cardano/git/partner-chain-cli/.index.mjs:7:67660)\n   
at file:///home/cardano/git/partner-chain-cli/.index.mjs:19:138434\n    
at T (file:///home/cardano/git/partner-chain-cli/.index.mjs:7:119995)\n    
at Object.run (file:///home/cardano/git/partner-chain-cli/.inex.mjs:7:122805)\n    
at bT (file:///home/cardano/git/partner-chain-cli/.index.mjs:7:125160)\n    
at tDa (file:///home/cardano/git/patner-chain-cli/.index.mjs:7:125470)\n    
at file:///home/cardano/git/partner-chain-cli/.index.mjs:7:125633\n    
at BD (file:///home/crdano/git/partner-chain-cli/.index.mjs:7:118775)\n    
at TT (file:///home/cardano/git/partner-chain-cli/.index.mjs:7:120396)\n    
at ile:///home/cardano/git/partner-chain-cli/.index.mjs:7:122834")
```
Let me try with non-extended  payment key.

**Comment by intertreeJK** [comment]
Given the propensity for people to extract their seed phrases for cli use using the cntools.sh script menu method, I would highly suggest adding compatibility for `"type": "PaymentExtendedSigningKeyShelley_ed25519_bip32",`

As I don't think many will be happy with going through required conversion steps to shorten their .skey files.

**Comment by stevanlohja** [comment]
ed25519_bip32 keys are not supported currently.

**Comment by intertreeJK** [comment]
Yes. This is why it is an issue. Hopefully support can be added soon.
